import ErrorAplicacion

class ExceptionC2(ErrorAplicacion):
    pass